version: '3.8'

services:
  adminui:
    image: nminhdangit/adminui:latest
    container_name: adminui
    networks:
      - nginx-proxy
    restart: always

networks:
  nginx-proxy:
    external: true
