version: '3.8'

services:
  adminui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - shared-network

networks:
  shared-network:
    external: true
