name: Build and publish image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  publish_images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build Docker image
      run: docker build . --file Dockerfile -t nminhdangit/adminui:latest

    - name: Push Docker image
      run: docker push nminhdangit/adminui:latest
